apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    tier: database
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
    tier: database

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
    tier: database

spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
        tier: database
    spec:
      containers:
        - name: postgres
          image: postgres
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - configMapRef:
                name: postgres-config
#          env:
#            - name: POSTGRES_USER
#              valueFrom:
#                secretKeyRef:
#                  name: postgres-credentials
#                  key: postgres_user
#            - name: POSTGRES_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: postgres-credentials
#                  key: postgres_password
#            - name: POSTGRES_DB
#              valueFrom:
#                configMapKeyRef:
#                  name: postgres-conf
#                  key: name

          ports:
            - containerPort: 5432
              name: postgres
